#########################################
# AlexKris Rules - Kuro
# License: AGPL-3.0
# Homepage: https://github.com/AlexKris/rules
#
# Kuro Games direct routing overlay.
#########################################
.kurogame.com
.kurogames.com
.kurobbs.com
.aki-game.com
.aki-game2.com
.kurogames-global.com
.kurogame.xyz
