from __future__ import annotations

import sys
import unittest
from pathlib import Path
from unittest.mock import patch


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import build_rules  # noqa: E402


class SKKMarkerDetectionTests(unittest.TestCase):
    def test_dynamic_marker_is_filtered_and_regular_skk_domains_remain(self) -> None:
        current_marker = "7h15_ru1353t_1s_m4d3_by_5ukk4w.skk.moe"
        legacy_marker = "7h1s_rul35et_i5_mad3_by_5ukk4w-ruleset.skk.moe"
        lines = [
            "# generated by SKK",
            f"DOMAIN,{current_marker}",
            "DOMAIN,cdn.skk.moe",
            "DOMAIN,ruleset.skk.moe",
            "DOMAIN-SUFFIX,skk.moe",
            f"DOMAIN,{legacy_marker}",
            f"DOMAIN,{current_marker}",
        ]
        config = {
            "source_marker_domains": [legacy_marker],
            "sources": {
                "skk": {
                    "kind": "non-ip",
                    "urls": [
                        "https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/master/List/non_ip/global.conf"
                    ],
                }
            },
        }

        with patch.object(build_rules, "read_configured_lines", return_value=lines):
            loaded, _ = build_rules.load_source_rules(config)

        values = {rule.value for rule in loaded["skk"]}
        self.assertNotIn(current_marker, values)
        self.assertNotIn(legacy_marker, values)
        self.assertIn("cdn.skk.moe", values)
        self.assertIn("ruleset.skk.moe", values)
        self.assertIn("skk.moe", values)

    def test_bare_domainset_marker_is_detected(self) -> None:
        marker = "7h15_ru1353t_1s_m4d3_by_5ukk4w.skk.moe"
        config = {
            "source_marker_domains": [],
            "sources": {
                "skk-domainset": {
                    "kind": "domainset",
                    "urls": [
                        "https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/master/List/domainset/cdn.conf"
                    ],
                }
            },
        }

        with patch.object(
            build_rules,
            "read_configured_lines",
            return_value=[marker, ".cdn.skk.moe", "img.skk.moe"],
        ):
            loaded, _ = build_rules.load_source_rules(config)

        values = {rule.value for rule in loaded["skk-domainset"]}
        self.assertNotIn(marker, values)
        self.assertIn("cdn.skk.moe", values)
        self.assertIn("img.skk.moe", values)

    def test_non_skk_source_does_not_apply_dynamic_marker_detection(self) -> None:
        domain = "first-rule.skk.moe"
        config = {
            "source_marker_domains": [],
            "sources": {
                "other": {
                    "kind": "non-ip",
                    "urls": ["https://example.com/rules.conf"],
                }
            },
        }

        with patch.object(
            build_rules,
            "read_configured_lines",
            return_value=[f"DOMAIN,{domain}"],
        ):
            loaded, _ = build_rules.load_source_rules(config)

        self.assertEqual([domain], [rule.value for rule in loaded["other"]])


if __name__ == "__main__":
    unittest.main()
