DOMAIN-SUFFIX,apple.com.cn
DOMAIN-SUFFIX,cn.apple.com
DOMAIN-SUFFIX,icloud.com.cn
DOMAIN-SUFFIX,cn.ls.apple.com
DOMAIN,api.smoot.apple.cn
DOMAIN-SUFFIX,cn-ssl.ls.apple.com
DOMAIN,gs-loc-cn.apple.com
DOMAIN-SUFFIX,gspe19-cn-ssl.ls.apple.com
DOMAIN,appleintelligencefeedback.care.apple.com
DOMAIN-SUFFIX,me.com
DOMAIN-SUFFIX,apple.co
DOMAIN-SUFFIX,apple.com
DOMAIN-SUFFIX,appsto.re
DOMAIN-SUFFIX,apple.news
DOMAIN-SUFFIX,icloud.com
DOMAIN-SUFFIX,itunes.com
DOMAIN-SUFFIX,aaplimg.com
DOMAIN-SUFFIX,appstore.com
DOMAIN-SUFFIX,apple-dns.net
DOMAIN-SUFFIX,cdn-apple.com
DOMAIN-SUFFIX,apple-mapkit.com
DOMAIN-SUFFIX,apple-cloudkit.com
DOMAIN-SUFFIX,icloud-content.com
DOMAIN-SUFFIX,organicfruitapps.com
DOMAIN-SUFFIX,push-apple.com.akadns.net
DOMAIN-SUFFIX,is1-ssl.mzstatic.com
DOMAIN-SUFFIX,time.apple.com
