DOMAIN,news-assets.apple.com
DOMAIN,events-live.apple.com
DOMAIN,events-delivery.apple.com
DOMAIN,static.ess.apple.com
DOMAIN,pba.apple.com
DOMAIN,statici.icloud.com
DOMAIN-SUFFIX,apple.news
DOMAIN-SUFFIX,news-edge.apple.com
DOMAIN-SUFFIX,news-client.apple.com
DOMAIN-SUFFIX,news-events.apple.com
DOMAIN-SUFFIX,mask.icloud.com
DOMAIN-SUFFIX,mask-h2.icloud.com
DOMAIN-SUFFIX,mask-api.icloud.com
DOMAIN-SUFFIX,developer.apple.com
DOMAIN-SUFFIX,appstoreconnect.apple.com
DOMAIN-SUFFIX,discussions.apple.com
DOMAIN-SUFFIX,devstreaming-cdn.apple.com
DOMAIN-SUFFIX,devimages-cdn.apple.com
DOMAIN-SUFFIX,adcdownload.apple.com
